/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
       /* int n=s.length();
        vector<int> count(26); //USING DICTIONARY
        for(int i=0;i<=n;i++){
            if(i==n){
               count[t[i]-'a']--;
            }
            else{
               count[s[i]-'a']++;
               count[t[i]-'a']--;
            }
        }
        
        char ans;
        for(int i=0;i<26;i++){
            if(count[i] < 0){
                ans = 'a' + i;
                break;
            }
        }
        
        return ans;*/
        /*
        int n = s.length();  //USING XOR
        
        char ans = 0;
        
        for(int i=0;i<=n;i++){
            if(i==n){
                ans^=t[i];
            }
            else{
                ans^=s[i];
                ans^=t[i];
            }
        }
        
        return ans;*/
         // USING DIFFERENCE BETWEEN SUM OF ASCII VALUES
        int n = s.length(),diff=0,diff1=0;
        char ans;
        
        for(int i=0;i<=n;i++){
            if(i==n){
                diff1+=t[i];
            }
            else{
                diff+=s[i];
                diff1+=t[i];
            }
        }
        ans = diff1 - diff;
        
        return ans;
    }
};
